---
title: "Phoebe Woodworth-Jefcoats, PhD"
format:
  closeread-html:
    cr-style:
      section-background-color: white
    theme: [zephyr, custom.scss]
---

```{r}
#| include: false
#| message: false
#| warning: false

# Global setup
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE
)
```

::::{.cr-section}

Education @cr-schools

:::{#cr-schools}

```{r}
  
# Load libraroes
library(dplyr)
library(ggplot2)
library(here)
library(ggiraph) # For interactive elements

# Load data
jobs <- read.csv(here("CV", "Data", "Employment.csv"))
school <- read.csv(here("CV", "Data", "Education.csv"))
labels <- read.csv(here("CV", "Data", "TimelineLabels.csv"))

labels_jobs <- labels |> filter(category == "job")
labels_school <- labels |> filter(category == "degree")

# This is tedious, but not sure of a better way
lj1 <- labels |> filter(category == "job_1")
lj2 <- labels |> filter(category == "job_2")
lj3 <- labels |> filter(category == "job_3")


# p <- ggplot(data = jobs,
#        aes(x = Start, y = End)) +
#   geom_point_interactive(
#     aes(tooltip = Position)
#   )
# 
# # Turn it into an interactive ggiraph plot
# girafe(ggobj = p)

# Build on previous plot
# which means replicating code from above
edu_interactive <- ggplot() +
geom_segment(data = jobs, aes(x = Start, y = 10,
                              xend = End, yend = 10,
                              color = Employer),
             linewidth = 3,
             show.legend = FALSE) +
geom_text(data = labels_jobs, aes(x = x, y = y, label = label),
          size = 4,
          hjust = 0,
          show.legend = FALSE) +
geom_text(data = lj1, aes(x = x, y = y, label = label),
          color = "#003087",
          size = 4,
          hjust = 0,
          show.legend = FALSE) +
geom_text(data = lj2, aes(x = x, y = y, label = label),
          color = "#77BDE7",
          size = 4,
          hjust = 0,
          show.legend = FALSE) +
geom_text(data = lj3, aes(x = x, y = y, label = label),
          color = "#3366cc",
          size = 4,
          hjust = 0,
          show.legend = FALSE) +
scale_y_continuous(
  limits = c(0, 100),
  position = "left") +
scale_x_continuous(
  limits = c(2002, 2026)) +
scale_color_manual(values = c("#77BDE7", "#3366cc", "#003087")) +
theme_void() +
coord_flip() +
# # new stuff added to plot
geom_point_interactive(data = school, aes(x = Date, y = 10, tooltip = Focus),
           shape = 21, color = "white", fill = "black", size = 5, stroke = 0.7,
           show.legend = FALSE) +
geom_text(data = labels_school, aes(x = x, y = y, label = label),
          size = 4,
          hjust = 0,
          show.legend = FALSE)

girafe(ggobj = edu_interactive,
       options = list(
         opts_tooltip(
           opacity = 0.9
         )
       )
       )
```
:::

::::
